### ISSUE TITLE
AA Release Epic

### ISSUE THREAD

**Issue by rjmk** [nstack/nstack-docs#1]
Quick overview of good docs:
 - http://www.writethedocs.org/guide/writing/beginners-guide-to-docs/
 
 Some famously good doc inspirations:
 - https://stripe.com/docs
 - https://docs.djangoproject.com/en/1.10/
 - https://help.shopify.com/api
 
 So I propose a rough structure of:

- [Overview](6) 
- [Concepts](7) 
- [Installation](10)
- [Quick Start](4)
- [Architecture Overview](5)
- [Examples / 'Cookbook'](2)
- [Reference](11)

from nstackcom/nstack#211

**Comment by rjmk** [comment]
I like the cookbook a lot. What do we ultimately want it to look like? What is a good MVP for that?

**Comment by lanthias** [comment]
I agree it's nice, though ultimately we may not have time for Friday, so we could do it last if we do have time and keep adding to it. Although an MVP could be a link to a GH repo, or even just a workflow file?
