### ISSUE TITLE
Complete reference for IDL, DSL, and sources and sinks

### ISSUE THREAD

**Issue by lanthias** [nstack/nstack-docs#11]
## User Story
- As a user, I want an overall reference on supported commands, supported sources and sinks, and API documentation so I can build things.

## Acceptance Criteria

- [x] API reference for the CLI
- [x] Module structure
- [x] IDL and DSL reference
- [x] Supported Integrations (e.g. Sources and Sinks)

**Comment by lanthias** [comment]
This still needs triage for sources, sinks, idl, and dsl.

**Comment by lanthias** [comment]
@feuerbach helpfully added documentation around sources and sinks in #19

**Comment by UnkindPartition** [comment]
The language reference is now merged (#29), closing.
