### ISSUE TITLE
Quick-Start

### ISSUE THREAD

**Issue by lanthias** [nstack/nstack-docs#4]
## User Story
* As a nstack developer, I want to be able to jump into building something on NStack without reading the entire documentation and 'learn by doing'.
* As an interested customer, I want to see how you build things on NStack so I can understand how I use it in my organisation.

## Notes 
I want thinking of something like, but some steps might be redundant?
- Quick Start
   - Step 1. Build a module
   - Step 2. Build a workflow from sources and sinks
   - Step 3. Start a workflow

## Questions
* Lump Step 3 into Step 2?

**Comment by rjmk** [comment]
I think on 2&3, do DSL in a workflow file first and then reveal the `start` command on the CLI takes any DSL expression which evaluates to a workflow?

Is

```
// workflow.nml
def fooSource = source(http:///foo : Text)
def myWorkflow = fooSource | someModule.numChars | sink(stdout:// : Integer)
```

going to work in AA, or will it fail because `fooSource` is not defined by the time `myWorkflow` is evaluated (cc/ @NickPollard)?

If it fails, I think I'll just go with CLI and not mention that it 'can' be done in the DSL

**Comment by lanthias** [comment]
Yes good question.

There is the question of how we want to structure this. For instance, I find myself creating a `sources` and a `sinks` module where I define my sources and sinks, and then building a separate workflow from them.

I agree you should show you can either put DSL in a file or do it manually. There could be an argument that doing it manually first is less of a barrier to entry for the first-time user though?

**Comment by rjmk** [comment]
> There could be an argument that doing it manually first is less of a barrier to entry for the first-time user though?

I think it depends on if (1) involves editing / creating some IDL/DSL. Were you envisaging just calls to the build command or lifecycle from init?

**Comment by rjmk** [comment]
I think looking at workflow DSL files might be better off after nstackcom/nstack#114. I'm at least going to hold off on it for my first pass at this

**Comment by lanthias** [comment]
We have a v1 of this, so closing and reopening another issue for more advanced quick start
