### ISSUE TITLE
Architecture Overview

### ISSUE THREAD

**Issue by lanthias** [nstack/nstack-docs#5]
## User Story
* As a tech-buyer, I want to understand how NStack is built, where it lives, and how it would fit into my organisation

## Acceptance Criteria
* Some visual diagram would be nice
* A description of the server and CLI

**Comment by rjmk** [comment]
👍 on diagram -- does it need to be UML though?

**Comment by lanthias** [comment]
No

**Comment by lanthias** [comment]
Added diagrams - closing
